### ISSUE TITLE
Refactor cdk_stack.py

### ISSUE THREAD

**Issue by jvntf** [NASA-IMPACT/cloud-optimized-data-pipelines#75]
File has gotten long and messy. should be refactored.

**Comment by leothomas** [comment]
[This article](https://docs.aws.amazon.com/cdk/v2/guide/best-practices.html) might be helpful as inspiration for refactoring. The approach they describe is a slight departure from the the way Dev Seed typically structures CDK based applications, but we've taken this approach on delta-backend, and the organization feels pretty intuitive. 

The idea is, instead of separating your application's source code and your CDK deployment code, you should structure your app as a series of CDK constructs, each with their own sub-folder. Each sub-folder has it's own infrastructure (CDK) code **and** runtime code. Eg:  [delta-backend raster api construct](https://github.com/NASA-IMPACT/delta-backend/tree/develop/raster_api): 
```bash
database/
    |_ infrastructure/
    |_ runtime/ # PGSTAC bootstrapping code here (runs when the stac gets deployed or updated)
stac_api/ 
    |_ infrastructure/
    |_ runtime/
networking/
    |_ infrastructure/ # VPC related resources (doesn't have any runtime code)
raster_api/
    |_ infrastructure/
        |_ config.py
        |_ construct.py # cdk code that defines a construct
    |_ runtime/
        |_ src/ # application code here
        |_ setup.py
        |_ Dockerfile
stack.py # CDK code that just pulls in the constructs of each high level component of the application
```

**Comment by jvntf** [comment]
closing in favor of #87
